# Use a smaller base image
FROM node:14-alpine AS builder

# Set working directory
WORKDIR /usr/src/app

# Copy only package.json and package-lock.json (if available) to leverage Docker caching
COPY package*.json ./

# Install dependencies using production flag to reduce image size
RUN npm ci --only=production

# Copy application source code
COPY . .

# Use a minimal runtime image
FROM node:14-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy dependencies and built application from the builder stage
COPY --from=builder /usr/src/app .

# Expose port
EXPOSE 3000

# Start application
CMD ["npm", "start"]
